AWSTemplateFormatVersion : '2010-09-09'
Description: Lambda Function.

Parameters:
  LambdaExecutionRole: 
    Type: String

Resources:
  WebMonitor:
    Type: AWS::Lambda::Function
    Properties:
      Code: src/handler
      Handler: handler.handler
      Runtime: python3.7
      Timeout: 10
      Role: !Ref LambdaExecutionRole
  LambdaScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
        Description: ’schedule event for lambda’
        ScheduleExpression: 'cron(0/1 * * * ? *)'
        State: ENABLED
        Targets:
          - Arn: !GetAtt WebMonitor.Arn
            Id: ScheduleEvent1Target
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebMonitor
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleEvent.Arn